### ISSUE TITLE
When logging in on a channel page you aren't not redirected back to channel page.

### ISSUE THREAD

**Issue by Eein** [Glimesh/glimesh.tv#649] opened 2021-04-21 02:52 UTC
during the team live stream i logged in, but i was not redirected back to the stream

have some suggestions here - will update later

**Comment by Cykotiq** [comment] 2021-04-21 05:16
duplicate of https://github.com/Glimesh/glimesh.tv/issues/182

**Closed** 2021-04-22 07:05 UTC
