### ISSUE TITLE
Video player not refreshed after disconnect and reconnect.

### ISSUE THREAD

**Issue by Eluzn** [Glimesh/glimesh.tv#573] opened 2021-03-15 12:14 UTC
Tested with Firefox 86:0 & Chrome Version 89.0.4389.82

When I stop streaming I am presented with the poster image. If I leave this view open and start streaming again the video element will not refresh to show the stream.

**Comment by haydenmc** [comment] 2021-03-15 20:14
Dupe of https://github.com/Glimesh/janus-ftl-plugin/issues/33

**Closed by haydenmc** 2021-03-15 20:14 UTC
